name: 1. Deploy_Azure_VM

on: 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to: dev, prod'
                required: true
                default: 'dev'

env:
    Location: "canadacentral"
    runNUmber: ${{ github.run_number }}

jobs:
    bicep_AzureVM_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


            # - name: Deploy Bicep template to Azure
            #   run: |
            #       az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP }} --template-file ./bicep/AzureVM.bicep --parameters adminUsername=${{ secrets.ADMIN_USERNAME }} adminPassword=${{ secrets.ADMIN_PASSWORD }} location=${{ env.Location }} runNumber=${{ env.runNUmber }}