name: 1. Deploy_Azure_VM

on: 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to: dev, prod'
                required: true
                type: choice
                options:
                    - dev
                    - prod
                default: 'dev'

env:
    Location: "canadacentral"
    runNUmber: ${{ github.run_number }}

permissions:
    id-token: write
    contents: read

jobs:
    bicep_AzureVM_deploy:
        environment: ${{ github.event.inputs.environment }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # - name: Example Step Using Secret
            #   run: echo "The secret value is ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            - name: Azure Login
              uses: azure/login@v2
              with:
                #   auth-type: IDENTITY
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy Azure VMs
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az deployment sub create \
                    --location ${{ env.Location }} \
                    --template-file template/main.bicep \
                    --name "AzureVMDeployment-${{ github.event.inputs.environment }}-${{ env.runNUmber }}" \
                    --parameters template/main.bicepparam \